### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by bt4ibwem8** [blogdron/EPGTV#2]
Can you make your script to work also in Windows? curl and gzip are available also for Windows. Now i get this error:
**EPGTV: Lua error: .../apps/mpv/current/portable_config/scripts/EPGTV/main.lua:110: attempt to concatenate a nil value**

**Comment by blogdron** [comment]
>curl and gzip are available also for Windows

I try maybe latter, Im no have windows, and Im no know how user install curl and gzip  on windows, inside mpv need full path to exacutable files, and now I dont know where store EPG cashe data, maybe for windows use script directory like `/EPGTV/epg/blablacachefile` 

>Lua error: .../apps/mpv/current/portable_config/scripts/EPGTV/main.lua:110: attempt to concatenate a nil value

Yes, becouse It find env variable `HOME` for create fullpath for EPG cache. Now Im just create error message for this case, no more. 

Okey. for future 

 * how you install gzip on windows?
   * fullpath to gzip zcat utilite?
 * how you install curl on windows?
   * fullpath to curl utilite?
 *  its okey if EPG cashe (250+ megabytes sometime!) inside script location directory? 
 
For me, just now imposible create port, Im no have windows,  If I do this, I will write to you about it here :)
And yes, I haven't taken time zones into account yet. So first I need to take time offsets into account. 
And I'm not a programmer, I'm just an amateur coder. So when I have time, I'll try. But I don't promise anything. ::)

**Comment by bt4ibwem8** [comment]
I installed gzip and curl with [scoop](https://scoop.sh/#/apps?q=gzip).
You can install Windows inside Virtual box on Linux :)
slaxml.lua file must be inside same folder as main.lua ?

**Comment by blogdron** [comment]
>slaxml.lua file must be inside same folder as main.lua ?

Yes, I can inject slaxml inside EPG lua file and distribute just EPG.lua file, not EPG directory, but Im use mpv recommendation for mpv plugin use directory because in best way, simple update from git, simple store files for plugin if need 

 * https://mpv.io/manual/master/#script-location  

This pludin it EPGTV directory with all files inside, it simple 

>You can install Windows inside Virtual box on Linux :)

Yep :D , but  it just won't be fast, I only have free time for fixing current bugs and shortcomings, as soon as I fix them I'll try to make a port, there's not much that needs to be changed there, but it's still necessary.

**Comment by blogdron** [comment]
@bt4ibwem8 

Oh my god, f*k*g windows not working :D Error on mpv installation, error on gzip installation... 
I won't try to run it on windows. (im try use win7 and win10 in virtual machine, error 0x000005 and others I don't even want to figure it out)
But I tried to do everything blindly, if it works I will leave a new code, if it doesn't work then I apologize, I don't use Windows and can't check the functionality. 
Anyway I will ask you to test, from you as a Windows user additional actions will be required.

 * install or download and unpack `gzip` some way (1005000 ways for installation)
 * install or download and unpack `curl` some way (1005000 ways for installation)

 - 1 - Clone `EPGTV` 
 - 2 - open `main.lua` in text editor
 - 3 - find `local config` and change bottom
      - 3.1 - `curl_path   = '/usr/bin/curl',`  change it to you **full path** to you curl executable file on windows
      - 3.2 - `zcat_path   = '/usr/bin/zcat',` change it to you **full path** to you zcat executable file on windows 
 - 4 - save `main.lua`
 - 5 - try run `mpv --script=EPGTV https://smolnp.github.io/IPTVru//IPTVru.m3u` (or use your playlist)
 - 6 **It works?**
     - if working, 
       - please press, 'h' after loading/parse and save tv data, you see tv program? (autoclose after 5 seconds)
       - please press, 'n' one more times, tv programs scrolled? (no autoclosed)
       - please press, 'esc' tv program closed?
       - please press 'g' you see message about all cache loaded?
       - close mpv 
         -  again open `mpv --script=EPGTV https://smolnp.github.io/IPTVru//IPTVru.m3u` (or use your playlist)
            - you see loading cashe?
            - afer loading cashe you see tv program? 
      - if not working
         - give for me error messages or full output log from terminal/console
         
--------------------------
Notice `zcat` usually contains in `gzip` utilites collection   

The essence is simple, I hope that it will be enough to simply specify the paths to the utilities that the script needs and everything should work right away.
There are many ways to install the necessary utilities, and even more ways to simply download archives with them and unpack them anywhere, so (if everything works for you) any Windows user will have to independently deal with the issue of installing the necessary utilities and manually add paths to them to the configuration. Better this way than nothing.

If we can't get this to work, then unfortunately I'll remove the Windows related changes. I have no way to test the script's functionality on Windows.

**Comment by blogdron** [comment]
Now you can try

 * clone or download + unpack `EPGTV` (with EPGTV directory) in  you `mpv` scripts directory 
 * open `conf.lua`
   * change `curl_path   = '/usr/bin/curl',` change it to you full path to you curl executable file on windows
   * change `zcat_path   = '/usr/bin/zcat'`, change it to you full path to you zcat executable file on windows
* run `mpv https://example.com/playlist.m3u`

need `mpv` stable version `0.38.0`

Maybe it works... maybe not 
Now I can't even check it.

**Comment by bt4ibwem8** [comment]
When streaming it shows "no have tv program for this channel" and i get this from Powershell:

EPGTV: EPGTV: Ignore external config ->  error loading module 'conf' from file 'C:/Users/lolo/scoop/apps/mpv/current/portable_config/scripts/EPGTV/conf.lua':
     EPGTV:     .../apps/mpv/current/portable_config/scripts/EPGTV/conf.lua:35: invalid escape sequence near ''C:'

 EPGTV: EPGTV:  Found TV program source http
     EPGTV: EPGTV:  Download TV program http
     EPGTV: EPGTV:  Failed get data from http

I get curl and zcat from busybox.exe and paste the path in conf.lua but not sure if this is correct way, just to point to busybox.exe because curl and zcat are inside this .exe file.

**Comment by blogdron** [comment]
show me config lines with paths please.

**Comment by bt4ibwem8** [comment]
zcat_path   = 'C:\Users\lolo\Desktop\busybox.exe'
curl_path   = 'C:\Users\lolo\Desktop\busybox.exe'

**Comment by blogdron** [comment]
No, need direct path for a specific utility.  And busybox no have curl subutilite. 

Curl you can get this 

 * https://curl.se/windows/

But `zcat` utilite from `gzip` utilites collection **maybe** from this

 * https://cygwin.com/install.html for example (I am a Linux user and I don't understand Windows at all)

Ohhh, maybe later im again try run it in virtual machine, and try forund simple way for get and install `curl`+`zcat`

**Comment by blogdron** [comment]
Other way 

install 

* msys2-x86_64-20221028.exe 
  * https://github.com/msys2/msys2-installer/releases/tag/2022-10-28

after install, auto opened terminal, now install `curl` + `gzip`

* write in msys2 terminal `pacman -S gzip` press enter and wait
* write in msys2 terminal `pacman -S curl` press enter and wait

Now you have paths for utilities in 
* `C:\\msys64\\usr\\bin\\zcat`
* `C:\\msys64\\usr\\bin\\curl`

I was able to install this and it should work, but I haven't been able to install mpv in a virtual machine yet lol I haven't tested it yet, no time for that

**Comment by bt4ibwem8** [comment]
I found i already have curl and zcat installed on win7 inside git. So i pasted this lines:
`curl_path   = 'C:\Users\lolo\scoop\apps\git\current\mingw64\bin\curl.exe',`
`zcat_path   = 'C:\Users\lolo\scoop\apps\git\current\usr\bin\zcat',`

Do you know if zcat must have .exe in Windows to be executable? Because curl file has .exe in the filename, but zcat does not... `gzip` is also installed.
Btw do i need zcat if i have EPG in .xml format? I think it should be needed only if .xml file is compressed, right?

**Comment by blogdron** [comment]
>Do you know if zcat must have .exe in Windows to be executable?

I dont know :(

>Btw do i need zcat if i have EPG in .xml format? 

No, if inside you m3u playlist you have url to plain xml , you no need `zcat`  you need only `curl` 

Try this (use double slash `\\` for windows path)

```
curl_path   = 'C:\\Users\\lolo\\scoop\\apps\\git\\current\\mingw64\\bin\\curl.exe',
```
P.S. I still don't have a chance to test this on a virtual machine.

**Comment by bt4ibwem8** [comment]
Still the same error `conf.lua:36: invalid escape sequence near ''C:'`
In terminal it shows "Found stream" and "Found TV channel" (same as without curl path) for each channel from the playlist, but epg does not work.
On laptop i have linux so i can test your script also there... I assume in Android mpv your script would not work :)

**Comment by blogdron** [comment]
>I assume in Android mpv your script would not work

This script have 3 non portable case

* 1 -  `curl` utilite  for get and load `EPG` URL or local EPG file 
* 2 - `zcat` utilite for unpack `zip/gzip` if `EPG` URL link is archive files `.zip` or `.gzip`
* 3 - paths for cashe location 
   *  in linux this `$HOME/.cache/EPGTV`
   *  in windows (experimental) it `%LOCALAPPDATA%\\EPGTV`
 
For script working need real path to specific utilities + writable path for cache. On Android no, it no can working, 
Unfortunately, there are no built-in mechanisms in mpv, at least for receiving files over the network, so I have to use other utilities, moreover, certain utilities are required since I pass them special keys inside the script. On Linux, everything should work, since it is very easy to install everything you need there and these will be native system utilities, in other cases, we have what we have. I would be glad for it to just work everywhere, but I do not have the necessary mpv API.

-----

If `conf.lua` have error, syntax error in this case, script **ignore all config**, and you `curl_patch` not used, you use double slashes '\\'? for curl patch? 

>"Found stream" and "Found TV channel"

This is good, script parse m3u and found EPG source link, but config have error, and config ignored,and script try call `/usr/bin/curl` default value for `curl_path`, need find way set correct direct path to executable file on windows. And maybe it start working.

**Comment by bt4ibwem8** [comment]
I have curl in PATH, so maybe you can just add second default option in script - directly call curl from the system

**Comment by blogdron** [comment]
@bt4ibwem8    It works :)  Now script dont use `zcat` and use `gzip` direclty you can use your `curl` and `gzip` utils, just add correct path to utils like in bottom, and bottom just my full test case, for other persons who be use `EPGTV`  

See  README footer or read this

I managed to
check the script's functionality for the `Windows 7` operating system only once.

## Preparation

* Download and unpack `static-mpv.7zip` to `static-mpv` (https://www.7-zip.org/)
* https://github.com/eko5624/mpv-win64/releases/tag/2024-04-01
* Download and unpack to `static-mpv\portable-config\scripts\EPGTV`
* https://github.com/blogdron/EPGTV/archive/refs/heads/master.zip
* Download and unpack to `C:\Program Files\curl`
* https://curl.se/windows/
* Download and unpack to `C:\Program Files\gzip`
* https://sourceforge.net/projects/gnuwin32/files/gzip/1.3.12-1/gzip-1.3.12-1-bin.zip/download
* Open file `static-mpv\portable-config\scripts\EPGTV\conf.lua`
* change values of `curl_path` and `gzip_path` to these

```lua
curl_path = 'C:\\Program Files\\curl\\bin\\curl.exe', -- set fullpath to you curl installation
gzip_path = 'C:\\Program Files\\gzip\\bin\\gzip.exe', -- set fullpath to you gzip installation
```

That's it, it should work now, in fact I described everything here in too much detail.
You only need to unzip the `EPGTV` directory with its contents in the script directory
of your `mpv` player, it can be in different places depending on your
version on `Windows` then you need to install `curl` and `gzip` and set the full paths
to them in the `EPGTV` configuration file and that's it. You can take these dependencies
from other places, and they may be needed in other ways, based on your case.


Please tell me if all okey and works

**Comment by bt4ibwem8** [comment]
Yes, it works now. However i got these issues:

1.  EPG data are poorly readable every second time when i press `Y` and `H`. Text is displayed like with very low brightness. When i press `Y` or `H` again, text is displayed correctly.
2.  Time and title of each program/show could be in yellow color (description text could stay in white color).
3. There could be some empty space between currently playing and future program (visually nicer).
4. Scrolling could be replaced with `middle mouse button` instead of `n`. When i scroll down this button it would show more/next epg data, when i scroll up this button it shows previous epg data.
5. If it is possible the script could be changed to access curl/gzip directly form system PATH so it would work out of box and users would not need to modify conf.lua file.

**Comment by blogdron** [comment]
>EPG data are poorly readable every second time when i press Y and H. Text is displayed like with very low brightness. When i press Y or H again, text is displayed correctly.

Try check, Im reorder draw calls, maybe it fix problem, if not there is nothing more I can do.
In mpv < 0.38.0 sometime dark background (for more text readable) drawing above text, although it should be displayed behind it.  If the problem is not fixed, just set the opacity of the shading background to maximum
```
background_opacity=90
```
or disable background  filling
```
background=false
```
That's all I can suggest doing.

>Time and title of each program/show could be in yellow color (description text could stay in white color).

Sorry, I like the current default for the colors of the titles of the programs that follow :D 
I specifically added the ability to change colors because people have different tastes in this regard, and some have special visual impairments.
You can change the colors to those that are more convenient for you. That's it, the titles of all future programs will become yellow, just like you want. 

```
upcoming_color  = '00FBFE'
```

>There could be some empty space between currently playing and future program (visually nicer).

Ok Im added one smaaal padding between top description and upcoming programms

>Scrolling could be replaced with middle mouse button instead of n. When i scroll down this button it would show more/next epg data, when i scroll up this button it shows previous epg data.

scroll is hack, It shouldn't have been there at all, it's based on sequentially deleting data from the top, which leads to the effect of scrolling, that's why it only scrolls down, and other buttons just reset everything to the beginning.

The program is shown only for today and tomorrow for speed, if I try to show more there will be brakes, here a lot has been done for the sake of maximum simplicity, this was the essence of reviving the script, in it and there a lot of things work slowly, and any changes in this part will entail rewriting half :D

All you can do is call the scroll down to any key convenient for you and that's it.

>If it is possible the script could be changed to access curl/gzip directly form system PATH so it would work out of box and users would not need to modify conf.lua file.

I wanted to, but no, in Linux it will just work, but in Windows it is not so, while I was trying to figure it out I downloaded more than a dozen different versions of utilities that are required for work, and half of them were launched by a bat script because they required libraries that are in their directory, if I use PATH then I will automatically receive the presence of the executable file, but I will need to build a full path to it, and sometimes in Windows there can be multiple copies of the same utility installed but different versions (for example MSYS2) and the script will take the first file it comes across for execution and as I have already found out sometimes this is not what is needed at all.

Therefore, no, the only 100% working option is to specify the file explicitly.


I doubt I'll have time to do anything else anytime soon, so if nothing else, you can close the issue :)

**Comment by bt4ibwem8** [comment]
I am using 0.38.0 version of mpv. 
1. How can i disable current time in the right up corner? I think this is causing the issue with poorly text visibility. Anyway we have time in system so no need to have it also in mpv 🙂. (background_opacity and background=false do not work).
2. I just discovered major issue that script do not parse epg data correctly. The time range is shifted forward so data are displayed incorrectly. For example Iptvnator is showing epg correctly.
3. How can i disable brackets () in the time range?

**Comment by blogdron** [comment]
>How can i disable current time in the right up corner?

Ok, add clock disable option for you. By default clock enabled, because in full screen need clock.
```lua
clock=false, -- false disable, true enable
```

>background_opacity and background=false do not work

It works, check you config (maybe you have syntax error). 

>I just discovered major issue that script do not parse epg data correctly. The time range is shifted forward so data are displayed incorrectly. For example Iptvnator is showing epg correctly.

All correct, but sometime, somewhere m3u not correct, epg not correct, local time not correct or other cases. 
And there are also specific cases when playlists are generated for a specific region (time zone) and some things are simply missing in the data, some programs that also rely on this and it turns out that those who are in a good time zone see everything as it should, and those who are located from it receive an offset, because those who generate the playlist and the data for it did not bother to add information about what the offset is relative to world time. There are just a bunch of huge nuances here, which are simply impossible to take into account automatically. I have everything correct, I calculate the time offset relative to the general world time, the same for the entire planet Earth, but yes, if there is no data for the calculation or they are specifically indicated in a convenient form for some part of the world, then it will be wrong. I can't do anything about it, I can only give a mechanism for setting this up. You said that in some program everything is correct, probably it specifies manual time shifting.

Im add for you and other person this option for custom shift timezone for tv, EPGTV all time recalculate tv time zone to you local timezone

```lua
force_time_shift=0, -- for example set 3 for add 3 hours or -3 to sub 3 hours
```

Moreover, sometime  inside `m3u` file (from local file or url) contain option `tvg-shift="+6"`  for example it option in EPGTV ignored by default, because often everything is written there except what is needed. But sometimes there really is a special time offset value there. Try turning it on

```lua
ignore_tvg_shift=false, -- set false for enable auto tvg-shift (if it option have in m3u)
```

And one more option, sometime inside EPG data tv channel have time but no have timezone or have incorrect time zone
Maybe try use this
```lua
ignore_time_zone=true, -- set tv timezone as you local timezone without timezone difference shift
```

I don't know which of these options will help you.
If you only use one playlist for TV programs, then it makes sense to simply manually add the time offset specified in the first option.


 You need to download EPGTV again, I just made the necessary changes


>How can i disable brackets () in the time range?

https://github.com/blogdron/EPGTV/blob/4347abebd2fa98360a8d220396b0bb343665bfb5/main.lua#L931

Learn 
  * https://mpv.io/manual/stable/#lua-scripting
  * https://www.lua.org/manual/5.4/
  * https://aegisub.org/docs/latest/ass_tags/

And just edit source code as you wish :D

**Comment by bt4ibwem8** [comment]
force_time_shift=-1 did the job and now it is showing correctly times. In m3u8 file i have only url for epg data, no other parameters. That software which correctly showing epg (by default, there are no options to modify epg, only put epg url) is [Iptvnator](https://github.com/4gray/iptvnator/) if you are interested to research this issue further.

**Comment by bt4ibwem8** [comment]
`force_time_shift=-1` did the job and now it is showing correctly times. In m3u8 file i have just url for epg data, no other parameters. That software which correctly showing epg (by default, there are no options to modify epg, only put epg url) is [Iptvnator](https://github.com/4gray/iptvnator/) if you are interested to research this issue further.
Btw how can i modify the line 931 in order to disable brakets? Maybe you could add `brakets=false` option into conf.lua :)
